.TH "GNOME-POMODORO" "1" "05 August,2014" "" ""

.SH NAME
gnome-pomodoro \- A simple time management utility
.SH SYNOPSIS

\fBgnome-pomodoro\fR [ \fB\fIOPTION\fB\fR ]

.SH "DESCRIPTION"
.PP
This manual page documents briefly the \fBgnome-pomodoro\fR command.
.PP
\fBgnome-pomodoro\fR is a GNOME utility that helps to manage time
according to the Pomodoro Technique. It intends to improve productivity and
focus by taking short breaks.
.SH "OPTIONS"
.PP
This program follows the usual GNU command line syntax, with long options
starting with two dashes (`-').
A summary of options is included below.
.TP
\fB          --preferences \fR
Open preferences window.
.TP
\fB          --no-default-window \fR
Run as background service.
.TP
\fB          --help \fR
Show a summary of options.
.PP
Other standard GNOME options not listed here are also supported.
.SH "SEE ALSO"
.PP
More information about \fBgnome-pomodoro\fR can be found at https://github.com/codito/gnome-pomodoro.
.SH "AUTHORS"
.PP
\fBgnome-pomodoro\fR has been written by Kamil Prusko <kamilprusko@gmail.com>; with the help of community contributions.
.PP
This manual page was written initially by Joseph Herlant <herlantj@gmail.com> for the Debian system (but may be used by others).
